version: "3"
services:
  postgres:
    container_name: nest-play
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data:rw
    env_file:
      - .env